### ISSUE TITLE
Issue with novaclient when running against OpenStack Ocata

### ISSUE THREAD

**Issue by akrzos** [ibmcb/cbtool#139]
I recently ran cbtool against OpenStack Ocata and in order to get cbtool to connect to my cloud I had to downgrade novaclient to 6.0.0 version.  Should the version of novaclient be pinned to avoid pulling a new version which might behave slightly different?

I will attempt to recreate the issue and post the problem I had with the newer version of novaclient pending time.

**Comment by akrzos** [comment]
Here is some terminal output to display the issue as I found it:

```
[speccloud@spec-cloud cbtool]$ pip freeze | grep novaclient
python-novaclient==8.0.0
[speccloud@spec-cloud cbtool]$ ./cb --soft_reset                                                                                                                                                                                 
Cbtool version is "4851ecb"
Parsing "cloud definitions" file..... "/home/speccloud/osgcloud/cbtool/lib/auxiliary//../..//configs/speccloud_cloud_definitions.txt" opened and parsed successfully.
Checking "Object Store".....An Object Store of the kind "Redis" (shared) on node 172.21.0.9, TCP port 6379, database id "0" seems to be running.
Checking "Log Store".....A Log Store of the kind "rsyslog" (private) on node 172.21.0.9, UDP port 5114 seems to be running.
Checking "Metric Store".....A Metric Store of the kind "MongoDB" (shared) on node 172.21.0.9, TCP port 27017, database id "metrics" seems to be running.
Checking "File Store".....A File Store of the kind "rsync" (private) on node 172.21.0.9, TCP port 873 seems to be running.
Executing "soft" reset: (killing all running toolkit processes and flushing stores) before starting the experiment......
Killing all processes... done
Flushing Object Store... done
Flushing Log Store... done

Checking for a running API service daemon.....API Service daemon was successfully started. The process id is ['28426'] (http://172.21.0.9:7070).
Checking for a running GUI service daemon.....GUI Service daemon was successfully started. The process id is [], listening on port 8080. Full url is "http://172.21.0.9:8080".
 status: VPN configuration for this cloud already generated: /home/speccloud/osgcloud/cbtool/lib/auxiliary//../../configs/generated/MYOPENSTACK_server-cb-openvpn.conf
 status: OpenStack connection parameters: username=admin, password=<omitted>, tenant=admin, cacert=None, insecure=False, region_name=regionOne, access_url=http://172.21.0.10:5000/v2.0, endpoint_type=publicURL
Request returned failure status: 401
Please attempt to execute the following : "python -c "from novaclient import client as novac;ct = novac.Client(2, 'admin', 'REPLACE_PASSWORD', 'admin', 'http://172.21.0.10:5000/v2.0', region_name='regionOne', service_type='co
mpute', endpoint_type='publicURL', cacert='None', insecure='False'); print ct.flavors.list()""
 status: VMC "regionOne" did not pass the connection test." : OpenStack connection failure: The request you have made requires authentication. (HTTP 401) (Request-ID: req-1b98dbde-8571-4838-9788-1c9c56249a3a)
The "osk" cloud named "MYOPENSTACK" could not be attached to this experiment: VMC "regionOne" did not pass the connection test." : OpenStack connection failure: The request you have made requires authentication. (HTTP 401) (R
equest-ID: req-1b98dbde-8571-4838-9788-1c9c56249a3a)
Usage: vmcattach <cloud_name> <identifier> [temp_attr_list = empty=empty] [mode] 
() exit
[speccloud@spec-cloud cbtool]$ sudo pip install python-novaclient==6.0.0
Collecting python-novaclient==6.0.0
  Using cached python_novaclient-6.0.0-py2.py3-none-any.whl
Requirement already satisfied: Babel>=2.3.4 in /usr/lib/python2.7/site-packages (from python-novaclient==6.0.0)
Requirement already satisfied: PrettyTable<0.8,>=0.7 in /usr/lib/python2.7/site-packages (from python-novaclient==6.0.0)
Requirement already satisfied: oslo.i18n>=2.1.0 in /usr/lib/python2.7/site-packages (from python-novaclient==6.0.0)
Requirement already satisfied: keystoneauth1>=2.10.0 in /usr/lib/python2.7/site-packages (from python-novaclient==6.0.0)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python2.7/site-packages (from python-novaclient==6.0.0)
Requirement already satisfied: simplejson>=2.2.0 in /usr/lib64/python2.7/site-packages (from python-novaclient==6.0.0)
Requirement already satisfied: oslo.utils>=3.16.0 in /usr/lib/python2.7/site-packages (from python-novaclient==6.0.0)
Requirement already satisfied: requests>=2.10.0 in /usr/lib/python2.7/site-packages (from python-novaclient==6.0.0)
Requirement already satisfied: pbr>=1.6 in /usr/lib/python2.7/site-packages (from python-novaclient==6.0.0)
Requirement already satisfied: oslo.serialization>=1.10.0 in /usr/lib/python2.7/site-packages (from python-novaclient==6.0.0)
Requirement already satisfied: iso8601>=0.1.11 in /usr/lib/python2.7/site-packages (from python-novaclient==6.0.0)
Requirement already satisfied: pytz>=0a in /usr/lib/python2.7/site-packages (from Babel>=2.3.4->python-novaclient==6.0.0)
Requirement already satisfied: positional>=1.1.1 in /usr/lib/python2.7/site-packages (from keystoneauth1>=2.10.0->python-novaclient==6.0.0)
Requirement already satisfied: stevedore>=1.20.0 in /usr/lib/python2.7/site-packages (from keystoneauth1>=2.10.0->python-novaclient==6.0.0)
Requirement already satisfied: netifaces>=0.10.4 in /usr/lib64/python2.7/site-packages (from oslo.utils>=3.16.0->python-novaclient==6.0.0)
Requirement already satisfied: funcsigs>=0.4; python_version == "2.7" or python_version == "2.6" in /usr/lib/python2.7/site-packages (from oslo.utils>=3.16.0->python-novaclient==6.0.0)
Requirement already satisfied: monotonic>=0.6 in /usr/lib/python2.7/site-packages (from oslo.utils>=3.16.0->python-novaclient==6.0.0)
Requirement already satisfied: netaddr!=0.7.16,>=0.7.13 in /usr/lib/python2.7/site-packages (from oslo.utils>=3.16.0->python-novaclient==6.0.0)
Requirement already satisfied: pyparsing>=2.1.0 in /usr/lib/python2.7/site-packages (from oslo.utils>=3.16.0->python-novaclient==6.0.0)
Requirement already satisfied: debtcollector>=1.2.0 in /usr/lib/python2.7/site-packages (from oslo.utils>=3.16.0->python-novaclient==6.0.0)
Requirement already satisfied: msgpack-python>=0.4.0 in /usr/lib64/python2.7/site-packages (from oslo.serialization>=1.10.0->python-novaclient==6.0.0)
Requirement already satisfied: wrapt in /usr/lib64/python2.7/site-packages (from positional>=1.1.1->keystoneauth1>=2.10.0->python-novaclient==6.0.0)
Installing collected packages: python-novaclient
  Found existing installation: python-novaclient 8.0.0
    Uninstalling python-novaclient-8.0.0:
      Successfully uninstalled python-novaclient-8.0.0
Successfully installed python-novaclient-6.0.0
[speccloud@spec-cloud cbtool]$ ./cb --soft_reset                                                                                                                                                                                 
Cbtool version is "4851ecb"
Parsing "cloud definitions" file..... "/home/speccloud/osgcloud/cbtool/lib/auxiliary//../..//configs/speccloud_cloud_definitions.txt" opened and parsed successfully.
Checking "Object Store".....An Object Store of the kind "Redis" (shared) on node 172.21.0.9, TCP port 6379, database id "0" seems to be running.
Checking "Log Store".....A Log Store of the kind "rsyslog" (private) on node 172.21.0.9, UDP port 5114 seems to be running.
Checking "Metric Store".....A Metric Store of the kind "MongoDB" (shared) on node 172.21.0.9, TCP port 27017, database id "metrics" seems to be running.
Checking "File Store".....A File Store of the kind "rsync" (private) on node 172.21.0.9, TCP port 873 seems to be running.
Executing "soft" reset: (killing all running toolkit processes and flushing stores) before starting the experiment......
Killing all processes... done
Flushing Object Store... done
Flushing Log Store... done

Checking for a running API service daemon.....API Service daemon was successfully started. The process id is ['28583'] (http://172.21.0.9:7070).
Checking for a running GUI service daemon.....GUI Service daemon was successfully started. The process id is [], listening on port 8080. Full url is "http://172.21.0.9:8080".
 status: VPN configuration for this cloud already generated: /home/speccloud/osgcloud/cbtool/lib/auxiliary//../../configs/generated/MYOPENSTACK_server-cb-openvpn.conf
 status: OpenStack connection parameters: username=admin, password=<omitted>, tenant=admin, cacert=None, insecure=False, region_name=regionOne, access_url=http://172.21.0.10:5000/v2.0, endpoint_type=publicURL

 OpenStack status: Checking if the ssh key pair "speccloud_default_spec_ssh" is created on VMC regionOne.... done
 OpenStack status: Checking if the security group "default" is created on VMC regionOne.... done

 OpenStack status: Checking if the floating pool "browbeat_public" can be found on VMC regionOne... done
 OpenStack status: Checking if the network "browbeat_private" can be found on VMC regionOne... done. This tenant network will be used as the default for provisioning.
 OpenStack status: Checking if the imageids associated to each "VM role" are registered on VMC regionOne.... done
 status: WARNING Image id for VM roles "mongos,redis,mongo_cfg_server,mongodb": "cb_ycsb" is NOT registered (attaching VMs with any of these roles will result in error).
         WARNING Image id for VM roles "giraphmaster,giraphslave": "cb_giraph" is NOT registered (attaching VMs with any of these roles will result in error).
         WARNING Image id for VM roles "xpingsender,xpingreceiver": "cb_xping" is NOT registered (attaching VMs with any of these roles will result in error).
         WARNING Image id for VM roles "driver_coremark,coremark": "cb_coremark" is NOT registered (attaching VMs with any of these roles will result in error).
         WARNING Image id for VM roles "specjbb": "cb_specjbb" is NOT registered (attaching VMs with any of these roles will result in error).
         WARNING Image id for VM roles "netserver,netclient": "cb_netperf" is NOT registered (attaching VMs with any of these roles will result in error).
         WARNING Image id for VM roles "filebench,driver_filebench": "cb_filebench" is NOT registered (attaching VMs with any of these roles will result in error).
         WARNING Image id for VM roles "driver_tradelite,client_tradelite": "cb_tradelite" is NOT registered (attaching VMs with any of these roles will result in error).
         WARNING Image id for VM roles "tinyvm,yatinyvm": "cb_nullworkload" is NOT registered (attaching VMs with any of these roles will result in error).
         WARNING Image id for VM roles "windows,client_windows": "cb_windows" is NOT registered (attaching VMs with any of these roles will result in error).
         WARNING Image id for VM roles "ddgen": "cb_ddgen" is NOT registered (attaching VMs with any of these roles will result in error).
         WARNING Image id for VM roles "lb,db2,driver_daytrader,geronimo,mysql,client_daytrader,was": "cb_daytrader" is NOT registered (attaching VMs with any of these roles will result in error).
         WARNING Image id for VM roles "linpack": "cb_linpack" is NOT registered (attaching VMs with any of these roles will result in error).
         WARNING Image id for VM roles "unixbench": "cb_unixbench" is NOT registered (attaching VMs with any of these roles will result in error).
         WARNING Image id for VM roles "iperfserver,iperfclient": "cb_iperf" is NOT registered (attaching VMs with any of these roles will result in error).
         WARNING Image id for VM roles "cn_hpc,fen_hpc": "cb_hpcc" is NOT registered (attaching VMs with any of these roles will result in error).
         WARNING Image id for VM roles "driver_hadoop,driver_netperf": "cb_hadoop" is NOT registered (attaching VMs with any of these roles will result in error).
         WARNING Image id for VM roles "nuttcpserver,nuttcpclient": "cb_nuttcp" is NOT registered (attaching VMs with any of these roles will result in error).
         WARNING Image id for VM roles "fio,driver_fio": "cb_fio" is NOT registered (attaching VMs with any of these roles will result in error)
 status: VMC "regionOne" was successfully tested.

The "osk" cloud named "MYOPENSTACK" was successfully attached to this experiment.
The experiment identifier is EXP-05-25-2017-12-53-59-PM-UTC

 status: Removing all VMs previously created on VMC "regionOne" (only VM names starting with "cb-speccloud-MYOPENSTACK").....
 status: Removing all VVs previously created on VMC "regionOne" (only VV names starting with "cb-speccloud-MYOPENSTACK").....
 status: The host list for VMC "regionOne" is empty ("discover_hosts" was set to "false"). Skipping Host OS performance monitor daemon startup
 status: Attribute "collect_from_host" was set to "false". Skipping Host OS performance monitor daemon startup
All VMCs successfully attached to this experiment.
(MYOPENSTACK) 
```

While trying to get python-novaclient 8.0.0 working I found I could change the tenant from the name 'admin' to the uuid but then I would encounter an error with cinderclient. 

```
[speccloud@spec-cloud cbtool]$ ./cb --soft_reset
Cbtool version is "4851ecb"
Parsing "cloud definitions" file..... "/home/speccloud/osgcloud/cbtool/lib/auxiliary//../..//configs/speccloud_cloud_definitions.txt" opened and parsed successfully.
Checking "Object Store".....An Object Store of the kind "Redis" (shared) on node 172.21.0.9, TCP port 6379, database id "0" seems to be running.
Checking "Log Store".....A Log Store of the kind "rsyslog" (private) on node 172.21.0.9, UDP port 5114 seems to be running.
Checking "Metric Store".....A Metric Store of the kind "MongoDB" (shared) on node 172.21.0.9, TCP port 27017, database id "metrics" seems to be running.
Checking "File Store".....A File Store of the kind "rsync" (private) on node 172.21.0.9, TCP port 873 seems to be running.
Executing "soft" reset: (killing all running toolkit processes and flushing stores) before starting the experiment......
Killing all processes... done
Flushing Object Store... done
Flushing Log Store... done

Checking for a running API service daemon.....API Service daemon was successfully started. The process id is ['28935'] (http://172.21.0.9:7070).
Checking for a running GUI service daemon.....GUI Service daemon was successfully started. The process id is [], listening on port 8080. Full url is "http://172.21.0.9:8080".
 status: VPN configuration for this cloud already generated: /home/speccloud/osgcloud/cbtool/lib/auxiliary//../../configs/generated/MYOPENSTACK_server-cb-openvpn.conf
 status: OpenStack connection parameters: username=admin, password=<omitted>, tenant=eee312b4ab6849d98e0356bb1037b84a, cacert=None, insecure=False, region_name=regionOne, access_url=http://172.21.0.10:5000/v2.0, endpoint_type=publicURL
Please attempt to execute the following : "python -c "from cinderclient.v2 import client as cinderc;ct = cinderc.Client('admin', 'REPLACE_PASSWORD', 'eee312b4ab6849d98e0356bb1037b84a', 'http://172.21.0.10:5000/v2.0', region_name='regionOne', service_type='volume', endpoint_type='publicURL', cacert='None', insecure='False'); print ct.volumes.list()""
 status: VMC "regionOne" did not pass the connection test." : OpenStack connection failure: The request you have made requires authentication. (HTTP 401)
The "osk" cloud named "MYOPENSTACK" could not be attached to this experiment: VMC "regionOne" did not pass the connection test." : OpenStack connection failure: The request you have made requires authentication. (HTTP 401)
Usage: vmcattach <cloud_name> <identifier> [temp_attr_list = empty=empty] [mode] 
() 
```

**Comment by hinesmr** [comment]
@akrzos If this is still a problem, please reopen.

**Comment by suryaprabhakar** [comment]
I am hitting this issue. Is there any fix?

**Comment by akrzos** [comment]
> I am hitting this issue. Is there any fix?

On the cbtool harness node you can run:

```
sudo pip install python-novaclient==6.0.0
```

**Comment by suryaprabhakar** [comment]
I have that already in place . python-novaclient (6.0.0)

**Comment by suryaprabhakar** [comment]
python -c "from novaclient import client as novac;ct = novac.Client(2, 'admin', 'blahblahblahh', 'admin', 'http://10.10.10.10:5000/v2.0/', region_name='regionOne', service_type='compute', endpoint_type='publicURL', cacert='None', insecure='True'); print ct.flavors.list()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/novaclient/v2/flavors.py", line 132, in list
    return self._list("/flavors%s%s" % (detail, query_string), "flavors")
  File "/usr/lib/python2.7/site-packages/novaclient/base.py", line 249, in _list
    resp, body = self.api.client.get(url)
  File "/usr/lib/python2.7/site-packages/novaclient/client.py", line 480, in get
    return self._cs_request(url, 'GET', **kwargs)
  File "/usr/lib/python2.7/site-packages/novaclient/client.py", line 436, in _cs_request
    self.authenticate()
  File "/usr/lib/python2.7/site-packages/novaclient/client.py", line 593, in authenticate
    auth_url = self._v2_auth(auth_url)
  File "/usr/lib/python2.7/site-packages/novaclient/client.py", line 684, in _v2_auth
    return self._authenticate(url, body)
  File "/usr/lib/python2.7/site-packages/novaclient/client.py", line 697, in _authenticate
    **kwargs)
  File "/usr/lib/python2.7/site-packages/novaclient/client.py", line 431, in _time_request
    resp, body = self.request(url, method, **kwargs)
  File "/usr/lib/python2.7/site-packages/novaclient/client.py", line 425, in request
    raise exceptions.from_response(resp, body, url, method)
novaclient.exceptions.Unauthorized: The request you have made requires authentication. (HTTP 401)
