### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by bphu** [ibmcb/cbtool#63]
It seems that some commands are still undocumented:

(CSFSM2PVC) help airun
Traceback (most recent call last):
  File "./cb", line 143, in <module>
    main()
  File "./cb", line 137, in main
    _cmd_processor.cmdloop()
  File "/usr/lib64/python2.6/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib64/python2.6/cmd.py", line 219, in onecmd
    return func(arg)
  File "/root/cloudbench/lib/auxiliary/cli.py", line 1011, in do_help
    Cmd.do_help(self, args)
  File "/usr/lib64/python2.6/cmd.py", line 313, in do_help
    func()
TypeError: help() takes exactly 1 argument (0 given)

**Comment by maugustosilva** [comment]
Fixed in commit 35307ece5200108412ab74406328216978fea2ba.
